language: python

python:
  - "3.6"

sudo: required

addons: 
  hosts:
    - dovecot.travis.dev

env:
  global:
    - IMAP_SERVER=dovecot.travis.dev
    - IMAP_USERNAME=user@dovecot.com
    - IMAP_PASSWORD=pwd
    - PROXY_PORT=8002

install:
  - pip3 install -r requirements.txt
  - sh .travis/run_imap_server.sh

script:
  - python3 proxy/proxy.py -p "$PROXY_PORT" &
  - pid=$!
  - sleep 5
  - python3 tests/test_proxy.py "$IMAP_USERNAME" "$IMAP_PASSWORD" localhost -p "$PROXY_PORT"
  - python3 tests/test_sanitizer.py "$IMAP_USERNAME" "$IMAP_PASSWORD" localhost -p "$PROXY_PORT"
  - kill -s INT $pid

notifications:
  email:
    on_success: change
    on_failure: change