language: python

python:
  - "3.6"

sudo: required

addons: 
  hosts:
    - dovecot.travis.dev

env:
  global:
    - IMAP_SERVER=dovecot.travis.dev
    - IMAP_SERVER_PORT=143
    - IMAP_USERNAME=user@dovecot.com
    - IMAP_PASSWORD=pwd

install:
  - pip3 install -r requirements.txt
  - sh .travis/run_imap_server.sh

script:
  - sudo python3 proxy/proxy.py
  - python3 tests/test_proxy.py "$IMAP_USERNAME" "$IMAP_PASSWORD" "$IMAP_SERVER"

notifications:
  email:
    on_success: change
    on_failure: change