language: python

python:
  - "3.6"

sudo: required

addons: 
  hosts:
    - dovecot.travis.dev

env:
  global:
    - IMAP_SERVER=dovecot.travis.dev
    - IMAP_USERNAME=user@dovecot.com
    - IMAP_PASSWORD=pwd
    - PROXY_PORT=8002

install:
  - sh .travis/run_imap_server.sh
  - python3 setup.py install
  - pip3 install -r requirements.txt

script:
  - start.py -p "$PROXY_PORT" &
  - pid=$!
  - sleep 5
  - test_proxy.py "$IMAP_USERNAME" "$IMAP_PASSWORD" localhost -p "$PROXY_PORT"
  - test_pycircleanmail.py "$IMAP_USERNAME" "$IMAP_PASSWORD" localhost -p "$PROXY_PORT"
  - kill -s INT $pid

notifications:
  email: false